baseurl = "http://miraglobal.com"
disqusShortname = ""
formspree = true
googleAnalytics = "UA-28439668-1"
languageCode = "en-us"
paginate = 10
theme = "vec"
title = "miraglobal.com"
[[menu.main]]
name = "references"
url = "/references"
weight = 2
[[menu.main]]
name = "contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "posts"
url = "/post"
weight = 1
[params]
avatar = "/img/Hardware-Chip-icon.png"
description = "Thoughts on Open Source and Education"
email = ""
githubid = ""
keywords = "opensource, education, scotland"
selfintro = "Thoughts on Open Source and Education"
