baseurl = "https://miraglobal.com"
disqusShortname = ""
formspree = true
googleAnalytics = "UA-57408564-1"
languageCode = "en-us"
paginate = 10
theme = "vec"
title = "miraglobal.com"
[[menu.main]]
name = "faq"
url = "/faq"
weight = 2
[[menu.main]]
name = "contact"
url = "/contact"
weight = 1
[[menu.main]]
name = "post"
url = "/post"
weight = 0
[params]
avatar = "img/avatar.jpg"
description = "Thoughts on Opensource and Education"
email = "timbuktuvariance@gmail.com"
githubid = "timbuktuvariance"
keywords = "opensource, education, scotland"
selfintro = "Thoughts on Opensource and Education"
