---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections: 
upload_dir: static/img
public_path: "/uploads/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
