---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: content/post
  label: Post
  create: all
- path: content
  label: Pages
  create: all
upload_dir: static/img
public_path: img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.45'
