---
label: default
hide_body: false
fields:
- name: toc
  label: Toc
  type: boolean
  hidden: false
  default: false
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: comments
  label: Comments
  type: boolean
  hidden: false
  default: false
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
pages:
- content/references.md
- content/post/materials-and-links.md
- content/post/robotics-and-hardware.md
- content/post/arcade.md
- content/post/map.md
- content/post/iot.md
- content/post/softwares-and-web.md
